export enum PlayerPersonalityTraitEnum {
  // Leadership & Work Ethic
  Leader = "Leader",
  HardWorker = "HardWorker",
  Lazy = "Lazy",
  Coachable = "Coachable",
  Uncoachable = "Uncoachable",
  Perfectionist = "Perfectionist",
  Slacker = "Slacker",
  Mentor = "Mentor",
  Respected = "RespectedByPeers",
  Delegator = "Delegator",
  Micromanager = "Micromanager",
  Punctual = "AlwaysPunctual",
  ChronicallyLate = "ChronicallyLate",

  // Ego & Motivation
  Humble = "Humble",
  Arrogant = "Arrogant",
  Diva = "Diva",
  TeamPlayer = "TeamPlayer",
  Selfish = "Selfish",
  FameDriven = "FameDriven",
  MoneyDriven = "MoneyDriven",
  GloryHunter = "GloryHunter",
  Loyal = "Loyal",
  Disloyal = "Disloyal",
  Entitled = "Entitled",
  SelfMotivated = "SelfMotivated",
  NeedsValidation = "NeedsValidation",
  PeoplePleaser = "PeoplePleaser",

  // Game Performance
  ClutchPerformer = "ClutchPerformer",
  Choker = "Choker",
  Inconsistent = "Inconsistent",
  GameChanger = "GameChanger",
  Dependable = "Dependable",
  MomentumPlayer = "MomentumPlayer",
  ConfidenceDriven = "ConfidenceDriven",
  PressureResistant = "PressureResistant",
  Overthinks = "OverthinksSituations",
  GameManager = "GameManager",

  // Conflict & Team Impact
  Disruptive = "Disruptive",
  LockerRoomCancer = "LockerRoomCancer",
  Mediator = "Mediator",
  Comedian = "Comedian",
  SilentProfessional = "SilentProfessional",
  DramaSeeker = "DramaSeeker",
  TeamDad = "TeamDad",
  Bully = "Bully",
  Instigator = "Instigator",
  Unifier = "Unifier",

  // Discipline & Lifestyle
  PartyAnimal = "PartyAnimal",
  CleanLiving = "CleanLiving",
  RuleFollower = "RuleFollower",
  RuleBreaker = "RuleBreaker",
  Focused = "Focused",
  Distracted = "EasilyDistracted",
  OffFieldIssues = "OffFieldIssues",
  MediaTrained = "MediaTrained",
  Reckless = "Reckless",
  StraightEdge = "StraightEdge",
  WorkLifeBalanced = "WorkLifeBalanced",
  Overworked = "Overworked",
  NightOwl = "NightOwl",
  EarlyRiser = "EarlyRiser",

  // Intelligence & Study Habits
  HighFootballIQ = "HighFootballIQ",
  LowFootballIQ = "LowFootballIQ",
  FilmJunkie = "FilmJunkie",
  Unprepared = "Unprepared",
  Studious = "Studious",
  Forgetful = "Forgetful",
  SystemThinker = "SystemThinker",
  Instinctive = "Instinctive",
  VisualLearner = "VisualLearner",
  NeedsRepetition = "NeedsRepetition",

  // Physical Traits (Mental Impact)
  InjuryProne = "InjuryProne",
  Durable = "Durable",
  SlowStarter = "SlowStarter",
  HotStarter = "HotStarter",
  AlwaysWarmedUp = "AlwaysWarmedUp",
  StrugglesWithConditioning = "StrugglesWithConditioning",
  BodyLanguageProblem = "NegativeBodyLanguage",
  VocalMotivator = "VocalMotivator",

  // Popularity & Brand
  FanFavorite = "FanFavorite",
  MediaDarling = "MediaDarling",
  MediaNightmare = "MediaNightmare",
  Marketable = "HighlyMarketable",
  Forgettable = "ForgettablePresence",
  SocialMediaSavvy = "SocialMediaSavvy",
  BrandBuilder = "BrandBuilder",
  AntiMedia = "AvoidsMedia",
  ReluctantStar = "ReluctantStar",
  Flashy = "Flashy",

  // Ambition & Career Goals
  WantsChampionships = "WantsChampionships",
  WantsStats = "WantsStats",
  WantsLegacy = "WantsLegacy",
  RingChaser = "RingChaser",
  CareerFocused = "CareerFocused",
  FamilyFocused = "FamilyFocused",
  PassionForGame = "PlaysForTheLoveOfTheGame",
  WantsToCoach = "WantsToCoachAfterCareer",
  WantsOut = "WantsOutOfTeam",
  LookingForNextContract = "LookingForNextBigContract",

  // Emotional Traits
  Resilient = "EmotionallyResilient",
  Moody = "Moody",
  Calm = "CalmUnderPressure",
  ShortTempered = "ShortTempered",
  Anxious = "Anxious",
  Optimist = "Optimist",
  Pessimist = "Pessimist",

  // Adaptability
  Adaptable = "Adaptable",
  SystemDependent = "SystemDependent",
  ThrivesInChaos = "ThrivesInChaos",
  NeedsStructure = "NeedsStructure",
}
