export enum PlayerPersonalityTraitEnum {
  // Leadership & Work Ethic
  Leader = "Leader",
  HardWorker = "Hard Worker",
  Lazy = "Lazy",
  Coachable = "Coachable",
  Uncoachable = "Uncoachable",
  Perfectionist = "Perfectionist",
  Slacker = "Slacker",
  Mentor = "Mentor",
  Respected = "Respected by Peers",
  Delegator = "Delegator",
  Micromanager = "Micromanager",
  Punctual = "Always Punctual",
  ChronicallyLate = "Chronically Late",

  // Ego & Motivation
  Humble = "Humble",
  Arrogant = "Arrogant",
  Diva = "Diva",
  TeamPlayer = "Team Player",
  Selfish = "Selfish",
  FameDriven = "Fame Driven",
  MoneyDriven = "Money Driven",
  GloryHunter = "Glory Hunter",
  Loyal = "Loyal",
  Disloyal = "Disloyal",
  Entitled = "Entitled",
  SelfMotivated = "Self-Motivated",
  NeedsValidation = "Needs Validation",
  PeoplePleaser = "People Pleaser",

  // Game Performance
  ClutchPerformer = "Clutch Performer",
  Choker = "Choker",
  Inconsistent = "Inconsistent",
  GameChanger = "Game Changer",
  Dependable = "Dependable",
  MomentumPlayer = "Momentum Player",
  ConfidenceDriven = "Confidence-Driven",
  PressureResistant = "Pressure Resistant",
  Overthinks = "Overthinks Situations",
  GameManager = "Game Manager",

  // Conflict & Team Impact
  Disruptive = "Disruptive",
  LockerRoomCancer = "Locker Room Cancer",
  Mediator = "Mediator",
  Comedian = "Comedian",
  SilentProfessional = "Silent Professional",
  DramaSeeker = "Drama Seeker",
  TeamDad = "Team Dad",
  Bully = "Bully",
  Instigator = "Instigator",
  Unifier = "Unifier",

  // Discipline & Lifestyle
  PartyAnimal = "Party Animal",
  CleanLiving = "Clean Living",
  RuleFollower = "Rule Follower",
  RuleBreaker = "Rule Breaker",
  Focused = "Focused",
  Distracted = "Easily Distracted",
  OffFieldIssues = "Off-Field Issues",
  MediaTrained = "Media Trained",
  Reckless = "Reckless",
  StraightEdge = "Straight Edge",
  WorkLifeBalanced = "Work-Life Balanced",
  Overworked = "Overworked",
  NightOwl = "Night Owl",
  EarlyRiser = "Early Riser",

  // Intelligence & Study Habits
  HighFootballIQ = "High Football IQ",
  LowFootballIQ = "Low Football IQ",
  FilmJunkie = "Film Junkie",
  Unprepared = "Unprepared",
  Studious = "Studious",
  Forgetful = "Forgetful",
  SystemThinker = "System Thinker",
  Instinctive = "Instinctive",
  VisualLearner = "Visual Learner",
  NeedsRepetition = "Needs Repetition",

  // Physical Traits (Mental Impact)
  InjuryProne = "Injury Prone",
  Durable = "Durable",
  SlowStarter = "Slow Starter",
  HotStarter = "Hot Starter",
  AlwaysWarmedUp = "Always Warmed Up",
  StrugglesWithConditioning = "Struggles with Conditioning",
  BodyLanguageProblem = "Negative Body Language",
  VocalMotivator = "Vocal Motivator",

  // Popularity & Brand
  FanFavorite = "Fan Favorite",
  MediaDarling = "Media Darling",
  MediaNightmare = "Media Nightmare",
  Marketable = "Highly Marketable",
  Forgettable = "Forgettable Presence",
  SocialMediaSavvy = "Social Media Savvy",
  BrandBuilder = "Brand Builder",
  AntiMedia = "Avoids Media",
  ReluctantStar = "Reluctant Star",
  Flashy = "Flashy",

  // Ambition & Career Goals
  WantsChampionships = "Wants Championships",
  WantsStats = "Wants Stats",
  WantsLegacy = "Wants Legacy",
  RingChaser = "Ring Chaser",
  CareerFocused = "Career Focused",
  FamilyFocused = "Family Focused",
  PassionForGame = "Plays for the Love of the Game",
  WantsToCoach = "Wants to Coach After Career",
  WantsOut = "Wants Out of Team",
  LookingForNextContract = "Looking for Next Big Contract",

  // Emotional Traits
  Resilient = "Emotionally Resilient",
  Moody = "Moody",
  Calm = "Calm Under Pressure",
  ShortTempered = "Short-Tempered",
  Anxious = "Anxious",
  Optimist = "Optimist",
  Pessimist = "Pessimist",

  // Adaptability
  Adaptable = "Adaptable",
  SystemDependent = "System Dependent",
  ThrivesInChaos = "Thrives in Chaos",
  NeedsStructure = "Needs Structure",
}
