export enum PlayerPositionEnum {
  QB = "Quarterback",
  RB = "Running Back",
  FB = "Fullback",
  WR = "Wide Receiver",
  TE = "Tight End",
  LT = "Left Tackle",
  LG = "Left Guard",
  C = "Center",
  RG = "Right Guard",
  RT = "Right Tackle",
  DE = "Defensive End",
  DT = "Defensive Tackle",
  NT = "Nose Tackle",
  EDGE = "Edge Rusher",
  LB = "Linebacker",
  MLB = "Middle Linebacker",
  OLB = "Outside Linebacker",
  ILB = "Inside Linebacker",
  CB = "Cornerback",
  FS = "Free Safety",
  SS = "Strong Safety",
  K = "Kicker",
  P = "Punter",
  LS = "Long Snapper",
  KR = "Kick Returner",
  PR = "Punt Returner"
}
