enum StaffRole {
  // Front Office
  TEAM_OWNER,
  TEAM_PRESIDENT,
  GENERAL_MANAGER,
  ASSISTANT_GENERAL_MANAGER,
  MEDIA_RELATIONS_MANAGER,
  CAP_SPECIALIST,

  // Scouting
  DIRECTOR_PLAYER_PERSONNEL,
  DIRECTOR_PRO_SCOUTING,
  DIRECTOR_COLLEGE_SCOUTING,
  PRO_SCOUT,
  NATIONAL_SCOUT,
  REGIONAL_SCOUT,
  COMBINE_SCOUT,

  // Medical
  HEAD_TRAINER,
  ASSISTANT_TRAINER,
  TEAM_DOCTOR,
  PHYSICAL_THERAPIST,
  SPORTS_PSYCHOLOGIST,
  NUTRITIONIST,

  // Analytics
  DATA_ANALYST,
  GAME_ANALYST,
  VIDEO_COORDINATOR,

  // Facilities
  EQUIPMENT_MANAGER,
  FACILITY_MANAGER,
  GROUNDSKEEPER,
  SECURITY_MANAGER
}