export const teamHistoriesMap: {
  [teamAbbreviation: string]: {
    yearFounded: number;
    allTimeWins: number;
    allTimeLosses: number;
    allTimeTies: number;
    playoffAppearances: number;
    superBowlAppearances: number;
    championships: number;
  };
} = {
  ARI: {
    yearFounded: 1898,
    allTimeWins: 593,
    allTimeLosses: 812,
    allTimeTies: 41,
    playoffAppearances: 7,
    superBowlAppearances: 1,
    championships: 0,
  },
  ATL: {
    yearFounded: 1966,
    allTimeWins: 403,
    allTimeLosses: 479,
    allTimeTies: 6,
    playoffAppearances: 15,
    superBowlAppearances: 1,
    championships: 0,
  },
  BAL: {
    yearFounded: 1996,
    allTimeWins: 260,
    allTimeLosses: 300,
    allTimeTies: 4,
    playoffAppearances: 15,
    superBowlAppearances: 3,
    championships: 3,
  },
  BUF: {
    yearFounded: 1960,
    allTimeWins: 505,
    allTimeLosses: 486,
    allTimeTies: 8,
    playoffAppearances: 12,
    superBowlAppearances: 4,
    championships: 0,
  },
  CAR: {
    yearFounded: 1995,
    allTimeWins: 217,
    allTimeLosses: 246,
    allTimeTies: 1,
    playoffAppearances: 7,
    superBowlAppearances: 1,
    championships: 0,
  },
  CHI: {
    yearFounded: 1920,
    allTimeWins: 798,
    allTimeLosses: 646,
    allTimeTies: 42,
    playoffAppearances: 22,
    superBowlAppearances: 1,
    championships: 1,
  },
  CIN: {
    yearFounded: 1968,
    allTimeWins: 403,
    allTimeLosses: 479,
    allTimeTies: 5,
    playoffAppearances: 14,
    superBowlAppearances: 2,
    championships: 0,
  },
  CLE: {
    yearFounded: 1946,
    allTimeWins: 544,
    allTimeLosses: 515,
    allTimeTies: 11,
    playoffAppearances: 12,
    superBowlAppearances: 4,
    championships: 0,
  },
  DAL: {
    yearFounded: 1960,
    allTimeWins: 569,
    allTimeLosses: 423,
    allTimeTies: 6,
    playoffAppearances: 35,
    superBowlAppearances: 8,
    championships: 5,
  },
  DEN: {
    yearFounded: 1960,
    allTimeWins: 472,
    allTimeLosses: 518,
    allTimeTies: 10,
    playoffAppearances: 22,
    superBowlAppearances: 8,
    championships: 3,
  },
  DET: {
    yearFounded: 1930,
    allTimeWins: 606,
    allTimeLosses: 709,
    allTimeTies: 34,
    playoffAppearances: 17,
    superBowlAppearances: 1,
    championships: 0,
  },
  GB: {
    yearFounded: 1919,
    allTimeWins: 810,
    allTimeLosses: 604,
    allTimeTies: 38,
    playoffAppearances: 35,
    superBowlAppearances: 5,
    championships: 4,
  },
  HOU: {
    yearFounded: 2002,
    allTimeWins: 146,
    allTimeLosses: 192,
    allTimeTies: 0,
    playoffAppearances: 7,
    superBowlAppearances: 0,
    championships: 0,
  },
  IND: {
    yearFounded: 1953,
    allTimeWins: 564,
    allTimeLosses: 510,
    allTimeTies: 8,
    playoffAppearances: 14,
    superBowlAppearances: 2,
    championships: 1,
  },
  JAX: {
    yearFounded: 1995,
    allTimeWins: 183,
    allTimeLosses: 253,
    allTimeTies: 0,
    playoffAppearances: 4,
    superBowlAppearances: 0,
    championships: 0,
  },
  KC: {
    yearFounded: 1960,
    allTimeWins: 547,
    allTimeLosses: 441,
    allTimeTies: 12,
    playoffAppearances: 30,
    superBowlAppearances: 5,
    championships: 4,
  },
  LV: {
    yearFounded: 1960,
    allTimeWins: 509,
    allTimeLosses: 480,
    allTimeTies: 11,
    playoffAppearances: 4,
    superBowlAppearances: 1,
    championships: 3,
  },
  LAC: {
    yearFounded: 1960,
    allTimeWins: 494,
    allTimeLosses: 495,
    allTimeTies: 11,
    playoffAppearances: 19,
    superBowlAppearances: 1,
    championships: 1,
  },
  LAR: {
    yearFounded: 1936,
    allTimeWins: 624,
    allTimeLosses: 606,
    allTimeTies: 21,
    playoffAppearances: 22,
    superBowlAppearances: 4,
    championships: 1,
  },
  MIA: {
    yearFounded: 1966,
    allTimeWins: 504,
    allTimeLosses: 408,
    allTimeTies: 4,
    playoffAppearances: 23,
    superBowlAppearances: 5,
    championships: 3,
  },
  MIN: {
    yearFounded: 1961,
    allTimeWins: 537,
    allTimeLosses: 438,
    allTimeTies: 11,
    playoffAppearances: 27,
    superBowlAppearances: 4,
    championships: 0,
  },
  NE: {
    yearFounded: 1960,
    allTimeWins: 545,
    allTimeLosses: 446,
    allTimeTies: 9,
    playoffAppearances: 30,
    superBowlAppearances: 11,
    championships: 6,
  },
  NO: {
    yearFounded: 1967,
    allTimeWins: 417,
    allTimeLosses: 480,
    allTimeTies: 5,
    playoffAppearances: 14,
    superBowlAppearances: 1,
    championships: 1,
  },
  NYG: {
    yearFounded: 1925,
    allTimeWins: 724,
    allTimeLosses: 663,
    allTimeTies: 34,
    playoffAppearances: 32,
    superBowlAppearances: 5,
    championships: 4,
  },
  NYJ: {
    yearFounded: 1960,
    allTimeWins: 433,
    allTimeLosses: 559,
    allTimeTies: 8,
    playoffAppearances: 14,
    superBowlAppearances: 1,
    championships: 0,
  },
  PHI: {
    yearFounded: 1933,
    allTimeWins: 638,
    allTimeLosses: 639,
    allTimeTies: 27,
    playoffAppearances: 27,
    superBowlAppearances: 3,
    championships: 1,
  },
  PIT: {
    yearFounded: 1933,
    allTimeWins: 681,
    allTimeLosses: 585,
    allTimeTies: 22,
    playoffAppearances: 33,
    superBowlAppearances: 8,
    championships: 6,
  },
  SEA: {
    yearFounded: 1976,
    allTimeWins: 383,
    allTimeLosses: 351,
    allTimeTies: 0,
    playoffAppearances: 16,
    superBowlAppearances: 3,
    championships: 1,
  },
  SF: {
    yearFounded: 1946,
    allTimeWins: 592,
    allTimeLosses: 512,
    allTimeTies: 14,
    playoffAppearances: 28,
    superBowlAppearances: 6,
    championships: 5,
  },
  TB: {
    yearFounded: 1976,
    allTimeWins: 299,
    allTimeLosses: 442,
    allTimeTies: 1,
    playoffAppearances: 12,
    superBowlAppearances: 2,
    championships: 2,
  },
  TEN: {
    yearFounded: 1960,
    allTimeWins: 479,
    allTimeLosses: 515,
    allTimeTies: 6,
    playoffAppearances: 14,
    superBowlAppearances: 1,
    championships: 0,
  },
  WAS: {
    yearFounded: 1932,
    allTimeWins: 641,
    allTimeLosses: 648,
    allTimeTies: 29,
    playoffAppearances: 24,
    superBowlAppearances: 5,
    championships: 3,
  },
};
